name:  lrp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - tensorboard=2.15.0
  - python=3.11.4
  - wget=1.21.4
  - pip
  - numpy
  - pytorch
  - torchvision
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - tqdm
  - types-tqdm
  - psutil
  - types-psutil
  - pylint
  - pycodestyle
  - mypy
  - yaml
  - pyyaml
  - types-pyyaml
  - imbalanced-learn
  - pip:
      - pydoclint
      - medmnist
      - rich
      - wget
